"""The NESO output eligibility report, generated from the registry (ADR-036 P-8).

Usage::

    python -m gridflow.connectors.neso_data_portal.eligibility --check [--path <md>]
    python -m gridflow.connectors.neso_data_portal.eligibility --write [--path <md>]

The committed report (``docs/neso_data_portal/eligibility.md`` by default,
relative to the current directory) is a pure function of the registry, so
``--check`` fails CI whenever a registry commit forgets to regenerate it, the
same discipline as ``registry yaml --check``.

**Effective eligibility of an output** (the one rule, :func:`effective_eligibility`):

1. the package is ``held`` -> every output of the package is held with the
   package's question and unit;
2. else the record's own ``eligibility`` when it sets one;
3. else ``eligible``.

Exit codes: 0 the committed file agrees (or was written), 1 drift, 2 usage.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING

from gridflow.connectors.neso_data_portal import registry as registry_module
from gridflow.connectors.neso_data_portal.files import replace_atomically
from gridflow.connectors.neso_data_portal.registry import Eligible, Held

if TYPE_CHECKING:
    from gridflow.connectors.neso_data_portal.registry import (
        Eligibility,
        FamilyEntry,
        PackageEntry,
        Registry,
    )

__all__ = [
    "CLOCK_LABELS",
    "DEFAULT_PATH",
    "DISPOSITION_ORDER",
    "effective_eligibility",
    "main",
    "render",
]

DEFAULT_PATH = Path("docs/neso_data_portal/eligibility.md")
DISPOSITION_ORDER: tuple[str, ...] = ("SILVER", "COVERED", "DOC", "GIS", "HOLD")

CLOCK_LABELS: dict[str, str] = {
    "ckan_last_modified": "CKAN last_modified of the captured file (ADR-030)",
    "capture_fallback": "gridflow capture time",
    "issue_time_evidenced": "vendor issue time per row",
}
"""``published_at`` per record vintage; ``available_at`` follows it (ADR-034/035)."""

_ELIGIBLE = Eligible(status="eligible")


def effective_eligibility(package: PackageEntry, family: FamilyEntry) -> Eligibility:
    """Return the publication eligibility of ``family``'s output (the P-8 rule).

    Args:
        package: The family's package.
        family: The family.

    Returns:
        The package's hold when the package is held, else the record's own
        eligibility when it sets one, else eligible.
    """
    if isinstance(package.eligibility, Held):
        return package.eligibility
    if family.record is not None and family.record.eligibility is not None:
        return family.record.eligibility
    return _ELIGIBLE


def describe_eligibility(eligibility: Eligibility) -> str:
    """One-line text of an eligibility: ``eligible`` or ``held: <question> (unit <unit>)``."""
    if isinstance(eligibility, Held):
        return f"held: {eligibility.question} (unit {eligibility.unit})"
    return "eligible"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _family_row(package: PackageEntry, family: FamilyEntry) -> str:
    dash = "—"
    if family.legacy:
        output = "bespoke silver"
        eligibility = describe_eligibility(effective_eligibility(package, family))
        latest = temporal = clock = dash
    elif family.record is not None:
        record = family.record
        output = "silver"
        eligibility = describe_eligibility(effective_eligibility(package, family))
        latest = (
            f"{record.latest} per {record.latest_partition}"
            if record.latest_partition is not None
            else record.latest
        )
        temporal = record.temporal.kind
        clock = CLOCK_LABELS[record.vintage]
    elif family.kind == "tabular":
        output = "ingest-only (no silver output)"
        eligibility = latest = temporal = clock = dash
    else:
        output = "catalogue only"
        eligibility = latest = temporal = clock = dash
    cells = (
        f"`{package.package}`",
        f"`{family.key}`",
        output,
        _cell(eligibility),
        latest,
        temporal,
        clock,
    )
    return "| " + " | ".join(cells) + " |"


def render(registry: Registry) -> str:
    """Render the eligibility report for ``registry`` (pure, deterministic).

    Args:
        registry: The loaded registry.

    Returns:
        The report text, LF line endings, ending in one newline.
    """
    lines = [
        "# NESO Data Portal: output eligibility",
        "",
        "<!-- Generated by `python -m gridflow.connectors.neso_data_portal.eligibility --write`"
        " from the registry. Do not edit by hand; `--check` fails CI on drift. -->",
        "",
        "Effective eligibility of an output (ADR-036 P-8): a held package holds every output"
        " of the package; else the record's own eligibility; else eligible. Packages are"
        " sorted by slug, families by key.",
        "",
        "## Families",
        "",
        "| Package | Family | Output | Eligibility | Latest | Temporal | Published clock |",
        "|---|---|---|---|---|---|---|",
    ]
    outputs: Counter[str] = Counter()
    held_outputs = 0
    for package in registry.packages:
        for family in sorted(package.families, key=lambda f: f.key):
            lines.append(_family_row(package, family))
            if family.legacy:
                outputs["bespoke"] += 1
            elif family.record is not None:
                outputs["recorded"] += 1
            elif family.kind == "tabular":
                outputs["ingest_only"] += 1
            else:
                outputs["files"] += 1
            if (family.legacy or family.record is not None) and isinstance(
                effective_eligibility(package, family), Held
            ):
                held_outputs += 1

    lines += [
        "",
        "## Resource dispositions per package",
        "",
        "| Package | Package eligibility | " + " | ".join(DISPOSITION_ORDER) + " |",
        "|---|---|" + "---|" * len(DISPOSITION_ORDER),
    ]
    totals: Counter[str] = Counter()
    held_packages = 0
    for package in registry.packages:
        tally: Counter[str] = Counter(resource.disposition.kind for resource in package.resources)
        totals.update(tally)
        held_packages += isinstance(package.eligibility, Held)
        cells = [
            f"`{package.package}`",
            _cell(describe_eligibility(package.eligibility)),
            *(str(tally[kind]) for kind in DISPOSITION_ORDER),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append(
        "| **Total** | | " + " | ".join(str(totals[kind]) for kind in DISPOSITION_ORDER) + " |"
    )

    families = sum(outputs.values())
    silver = outputs["bespoke"] + outputs["recorded"]
    lines += [
        "",
        "## Totals",
        "",
        f"- Packages: {len(registry.packages)} (held: {held_packages})",
        f"- Families: {families}: silver {silver} (bespoke {outputs['bespoke']}, recorded"
        f" {outputs['recorded']}), ingest-only {outputs['ingest_only']}, catalogue only"
        f" {outputs['files']}",
        f"- Silver outputs held: {held_outputs}",
        f"- Resources: {sum(totals.values())}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Entry point. Exit 0 agree or written, 1 drift, 2 usage."""
    parser = argparse.ArgumentParser(
        prog="python -m gridflow.connectors.neso_data_portal.eligibility"
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--path", type=Path, default=DEFAULT_PATH)
    args = parser.parse_args(argv)

    rendered = render(registry_module.load_registry())
    path: Path = args.path
    if args.write:
        path.parent.mkdir(parents=True, exist_ok=True)
        replace_atomically(path, rendered.encode("utf-8"))
        print(f"wrote {path}")
        return 0
    try:
        committed = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    except (OSError, UnicodeDecodeError) as exc:
        print(f"cannot read {path}: {exc}", file=sys.stderr)
        return 1
    if committed != rendered:
        print(
            f"{path} disagrees with the registry; run "
            "`python -m gridflow.connectors.neso_data_portal.eligibility --write`",
            file=sys.stderr,
        )
        return 1
    print(f"{path} agrees with the registry")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
